# Assignment 24

## Date : 26/02/2023

#### Consider the below code to answer further questions:

In [ ]:
import numpy as np
list_ = ['1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

#### Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

#### Answer:
No, there is no difference in the data type of variables list_ and array_list because the elements in the list are strings and the np.array() function converts them into a NumPy array of strings.

However, if the elements in the list were of different data types, the resulting NumPy array would have a data type that is determined by NumPy's type inference rules.

Here's the code to print the data types of list_ and array_list:

In [3]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

print("Data type of list_ variable:", type(list_))
print("Data type of array_list variable:", type(array_list))


Data type of list_ variable: <class 'list'>
Data type of array_list variable: <class 'numpy.ndarray'>


As you can see, the data type of list_ is list, whereas the data type of array_list is numpy.ndarray.

#### Q2. Write a code to print the data type of each and every element of both the variables list_ and array_list.

#### Answer:

In [5]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

# Print data types of list_ elements
print("Data types of list_ elements:")
for elem in list_:
    print(type(elem))

# Print data types of array_list elements
print("\nData types of array_list elements:")
for elem in array_list:
    print(type(elem))


Data types of list_ elements:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types of array_list elements:
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


#### Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)

#### Will there be any difference in the data type of the elements present in both the variables, list_ and array_list? If so then print the data types of each and every element present in both the variables, list_ and array_list.

#### Answer:
Yes, there will be a difference in the data type of the elements present in list_ and array_list when array_list is created with the dtype parameter set to int.

Here's the updated code:

In [6]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_, dtype=int)

# Print data types of list_ elements
print("Data types of list_ elements:")
for elem in list_:
    print(type(elem))

# Print data types of array_list elements
print("\nData types of array_list elements:")
for elem in array_list:
    print(type(elem))


Data types of list_ elements:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types of array_list elements:
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>


As you can see, the data type of each element in list_ is str, whereas the data type of each element in array_list is numpy.int64 because we explicitly set the dtype parameter of np.array() to int

#### Consider the below code to answer further questions:

import numpy as np

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list)

#### Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape

(ii) size

#### Answer:

In [10]:
import numpy as np

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list)
num_array.shape

(2, 3)

In [11]:
num_array.size

6

#### Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]

#### Answer:

In [12]:
import numpy as np

# Create a 3x3 array of zeros
zeros_array = np.zeros((3, 3))

# Print the zeros_array
print(zeros_array)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


#### Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

#### Answer:

In [13]:
import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.identity(5)

# Print the identity_matrix
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
